---
title: "index"
---

## My Word
有时候意外就是突然发现数据分析的代码全没了，但是还有个傻子陪着你熬夜
不知不觉一年半了，过去的日子就像水一样，在渴的时候解渴
今年不知道为什么脚疼完手疼，大概这是不能用科学解释的
就像这个晚上，虽然肘部疼痛犯了、代码没了、要刮台风了、要有pre了，但依然有一份美好

## Word of 傻子
最近又重温了一遍百年孤独，距离上一次看真的整整隔了十年，——没错，我四年级就已经看了。但是当时当然是看不懂的，过于复杂的人名和魔幻的情节，对年少的我来说实在门槛太高。要说给我幼小的心灵带来什么冲击的话，只是觉得果然经典就是不一样，小×文都高级好多（看过的都懂）。这次疫情隔离的三天里我重新再看起这本书，会有一种深深的共情和震撼，我翻了翻书柜里自己最近四年购入的书籍，“孤独”喜提主题名词。
可能我的孤独感要从童年追溯了，我接近双面的性格让不同的人对我印象天壤之别。有时候我都分不清楚哪个是本我，或许人性的本质就不应该被一种束缚。我的孤独，恰恰诞生在这一次次现实魔幻之中。最孤独的时候可能有很长一段时间，应该从高一慢慢就开始了，去参加文艺主持，去读文，去写自己的第一本书，我做着和周围格格不入的东西，虽然现在看起来无可厚非，但是在容不得一丝出错的塞道上，我显然让人觉得吊儿郎当。他们觉得我不够努力和认真，我只是觉得我太过孤独。
孤独到有段时间不敢看《红楼梦》这些描述由盛到衰的故事，更不必提《百年孤独》。于是它在我慢慢能够懂的日子里，我也没有去看。一放十年。
马尔克斯一直说他并不是魔幻形式主义作家，他描述的只是现实。很多吊诡的事情，在时代的巨轮下都曾被清清楚楚地碾压过，只是它们被压碎了，没有了，别人没见过不相信而已。
我们都看不见别人的人生。当然互联网朋友圈改变了这个，我们可以分享。但是分享多了又会发现，我们也并没有那么有闲情去看别人的人生。
今天想分享的魔幻现实主义是我居然恋爱一年半了，异地的日子聚少离多，相伴的时候眨眼一过，我更多的是看着电子屏幕对面的他，我们是彼此跨越两千公里，不顾台风（今天明天就是台风）暴雨（疫情还是要顾的，这次就因为市里一个阳了整整三天没见）都要见面的人。（隔离一结束就刮台风这件事真的很魔幻）。当然更加魔幻的是我们居然才恋爱一年半。感觉已经对彼此熟透了，很多事情还没有发生就会觉得他肯定会咋咋咋，但是很多时候又并不是的，我想可能哪怕过去几十年，一个你愿意用心去陪伴的人，身上都是会有新的东西蹦出来，让我感到新奇但又不陌生吧。
其实很久没有说这么多了，免得大家觉得我神神叨叨。但是不管魔幻也好，现实也罢，我很开心自己这次没有孤独，也期待自己的孤独在过去十年被涤荡成勇气，支撑起我们的百年。

